# BEGIN_KITTY_THEME
# Monokai Soda
#include current-theme.conf
# END_KITTY_THEME
#
# BEGIN_FONTS
font_family      ProFont IIx Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size        11.0
# END_FONTS

shell /usr/bin/fish
shell_integration no-cursor

cursor_shape           block
cursor_shape_unfocused hollow
cursor_trail 10 
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Put the following lines in your ~/.config/kitty/kitty.conf
foreground #e6e6e6
background #141414
color0 #282828
color1 #e85a4f
color2 #5fb36a
color3 #f6ce4e
color4 #5b82c7
color5 #e57aa4
color6 #64b8b4
color7 #e6e6e6
color8 #737373
color9 #ff6a6a
color10 #7ad48a
color11 #ffe07a
color12 #7fa2e6
color13 #f29bc1
color14 #7fd9d4
color15 #ffffff
cursor #e6e6e6
cursor_text_color #141414
selection_foreground none
selection_background #282828
tab_bar_background #0b0b0b
active_tab_foreground #e6e6e6
active_tab_background #141414
inactive_tab_foreground #737373
inactive_tab_background #0f0f0f
active_border_color #e6e6e6
inactive_border_color #e6e6e6

background_opacity 0.8
dynamic_background_opacity yes

map ctrl+shift+b remote_control set-background-opacity --toggle 1 


