backend = "glx";
vsync = true;
corner-radius = 10;
use-damage = false;
backend = "glx";
blur: {
  method = "dual_kawase";
  strength = 7;
  background = true;
  background-frame = false;
  background-fixed = false;
}
rounded-corners-exclude = [
    "window_type = 'dock'",
    "class_g = 'xmobar' ",
    "window_type = 'fullscreen'"]

animations = ({
    triggers = ["open"];
    preset = "slide-in";
    direction = "up";
    duration = 0.1;
},{
    triggers = ["close"];
    preset = "slide-out";
    direction = "up";
    duration = 0.1;
},{
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.2;
});

shadow = false
